apiVersion: v1
kind: Template
metadata:
  name: openshift-images-builder
parameters:
- name: BASE_IMAGE_VERSION
  description: Fedora base Image version, default is 27
  value: "27"
- name: OPENDHIFT_IMAGE_BUILD_VERSION
  value: v3.9
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fedora
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/library/fedora:${BASE_IMAGE_VERSION}
      name: ${BASE_IMAGE_VERSION}
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: origin-origin
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openshift/origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
      name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: origin-node
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openshift/node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
      importPolicy:
        scheduled: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: source
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: base
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: pre
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: origin
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: pre-node
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: node
    labels:
      template: openshift-images-builder
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      template: openshift-images-builder
    name: openvswitch
  spec:
    tags:
    - name: ${OPENDHIFT_IMAGE_BUILD_VERSION}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: source
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: source:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      contextDir: source
      git:
        uri: https://github.com/dsevost/origin-fedora
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: fedora:${BASE_IMAGE_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: fedora:${BASE_IMAGE_VERSION}
      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: base
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: base:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      contextDir: base
      git:
        uri: https://github.com/dsevost/origin-fedora
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: source:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: source:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
#    - imageChange: {}
#      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: pre
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: pre:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      dockerfile: |-
        FROM base:${OPENDHIFT_IMAGE_BUILD_VERSION}
        COPY tmp1/openshift /usr/bin/
        COPY tmp2/oc /usr/bin/oc
      images:
      - from:
          kind: ImageStreamTag
          name: origin-origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
        paths:
        - destinationDir: tmp1
          sourcePath: /usr/bin/openshift
        - destinationDir: tmp2
          sourcePath: /usr/bin/oc
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: base:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: origin-origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: base:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
#    - imageChange: {}
#      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: origin
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      contextDir: origin
      git:
        uri: https://github.com/dsevost/origin-fedora
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: pre:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: pre:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
#    - imageChange: {}
#      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: node-pre
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: pre-node:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      dockerfile: |-
        FROM origin
        COPY tmp1 /etc/
        COPY tmp2 /opt/
        COPY tmp3 /usr/
      images:
      - from:
          kind: ImageStreamTag
          name: origin-node:${OPENDHIFT_IMAGE_BUILD_VERSION}
        paths:
        - destinationDir: tmp1
          sourcePath: /etc/cni
        - destinationDir: tmp2
          sourcePath: /opt/cni
        - destinationDir: tmp3
          sourcePath: /usr/lib/systemd/system/origin-node.service.d
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: origin-node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: origin:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
#    - imageChange: {}
#      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: node
    labels:
      template: openshift-images-builder
  spec:
    runPolicy: SerialLatestOnly
    output:
      to:
        kind: ImageStreamTag
        name: node:${OPENDHIFT_IMAGE_BUILD_VERSION}
    source:
      contextDir: node
      git:
        uri: https://github.com/dsevost/origin-fedora
      type: Git
    strategy:
      dockerStrategy:
        env:
        - name: ZFS_REPO_FEDORA_REL
          value: ${BASE_IMAGE_VERSION}
        from:
          kind: ImageStreamTag
          name: pre-node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: pre-node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
#    - imageChange: {}
#      type: ImageChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      template: openshift-images-builder
    name: openvswitch
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: openvswitch:${OPENDHIFT_IMAGE_BUILD_VERSION}
    runPolicy: SerialLatestOnly
    source:
      contextDir: openvswitch
      git:
        uri: https://github.com/dsevost/origin-fedora
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: Docker
    triggers:
    - imageChange:
        from:
          kind: ImageStreamTag
          name: node:${OPENDHIFT_IMAGE_BUILD_VERSION}
      type: ImageChange
    - type: ConfigChange
