apiVersion: v1
kind: BuildConfig
metadata:
  name: node-pre
spec:
  output:
    to:
      kind: ImageStreamTag
      name: pre-node:latest
  source:
    dockerfile: |-
      FROM origin
      COPY tmp1 tmp2 tmp3 /root/tmp/
      COPY tmp1 /etc/
      COPY tmp2 /opt/
      COPY tmp3 /usr/
    images:
    - from:
        kind: ImageStreamTag
        name: origin-node:latest
      paths:
      - destinationDir: tmp1
        sourcePath: /etc/cni
      - destinationDir: tmp2
        sourcePath: /opt/cni
      - destinationDir: tmp3
        sourcePath: /usr/lib/systemd/system/origin-node.service.d
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: origin:latest
    type: Docker
  triggers:
  - imageChange:
      from:
        kind: ImageStreamTag
        name: origin-node:latest
    type: ImageChange
  - imageChange:
      from:
        kind: ImageStreamTag
        name: origin:latest
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: ImageStream
metadata:
  name: pre-node
spec:
  -
    name: latest
    referencePolicy:
      type: ""
